[package]
authors = ["anderejd <rajder@gmail.com>"]
description = "TODO: Write description"
edition = "2018"
license = "Apache-2.0/MIT"
name = "cargo-geiger-serde"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
