strategy:
  matrix:
    windows:
      imageName: 'windows-latest'
    macOS:
      imageName: 'macOS-latest'
    linux:
      imageName: 'ubuntu-latest'

pool:
  vmImage: $(imageName)

steps:
  - script: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      curl --proto '=https' --tlsv1.2 -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain stable
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Windows install rust
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: cargo build --all
    displayName: Cargo build
  - script: cargo test --all
    displayName: Cargo test
