[package]
name = "cargo-tree"
version = "0.4.1"
authors = ["Steven Fackler <sfackler@palantir.com>"]
license = "MIT/Apache-2.0"
description = "A Cargo subcommand that visualizes a crate's dependency graph in a tree-like format"
repository = "https://github.com/sfackler/cargo-tree"
readme = "README.md"

[dependencies]
cargo = { version = "0.10", git = "https://github.com/rust-lang/cargo" }
rustc-serialize = "0.3"
petgraph = "0.2"
