[package]
authors = ["anderejd <rajder@gmail.com>"]
categories = ["command-line-utilities", "development-tools", "development-tools::cargo-plugins", "parsing"]
description = "Detects usage of unsafe Rust in a Rust crate and its dependencies."
edition = "2018"
keywords = ["unsafe", "cargo", "plugin"]
license = "Apache-2.0/MIT"
name = "cargo-geiger"
readme = "README.md"
repository = "https://github.com/rust-secure-code/cargo-geiger"
version = "0.10.0"

[badges]
maintenance = { status = "experimental" }

[dependencies]
cargo = "0.43.1"
cargo-platform = "0.1.1"
colored = "1.9.3"
console = "0.10.0"
env_logger = "0.7.1"
geiger = { path = "../geiger", version = "0.4.4" }
petgraph = "0.5.0"
pico-args = "0.3.1"
walkdir = "2.3.1"

[features]
vendored-openssl = ["cargo/vendored-openssl"]

[dev-dependencies]
assert_cmd = "1.0.1"
better-panic = "0.2.0"
insta = "0.15.0"
regex = "1.3.6"
rstest = "0.6.1"
