[package]
name = "test4_workspace_with_virtual_manifest"
version = "0.1.0"
edition = "2018"

[workspace]
members = ["member1"]

[dependencies]
test1_package_with_no_deps = { path = "../test1_package_with_no_deps" }
