[package]
name = "geiger"
description = "Some library parts of cargo-geiger, decoupled from cargo."
version = "0.4.2"
edition = "2018"
authors = ["anderejd <rajder@gmail.com>"]
repository = "https://github.com/anderejd/cargo-geiger"
readme = "README.md"
keywords = ["unsafe"]
categories = ["development-tools", "parsing"]
license = "Apache-2.0/MIT"

[badges]
maintenance = { status = "experimental" }

[dependencies]
syn = { version = "1.0.14", features = ["parsing", "printing", "clone-impls", "full", "extra-traits", "visit"] }
proc-macro2 = "1.0.8"
